## YEML (YAML ExE Boss Extended Markup Language) Site Configuration.
title:	Blog – ExE Boss
author:	ExE Boss

url:	https://blog.exe-boss.tech
permalink:	/:year/:month/:day/:title

paginate:	5
paginate_path:	/page/:num

plugins:
    - jekyll-paginate

defaults:
    -
        scope:
            path:	""
        values:
            layout:	"default"
            include-footer:	false
            include-css:
            include-js:
            content-security-policy:
                -   name: "script-src"
                    value:
                        - "'self'"
                        - "https://exe-boss.tech"
                        - "https://cdnjs.cloudflare.com/"
                -   name: "style-src"
                    value:
                        - "'self'"
                        - "'unsafe-inline'"
                        - "https://exe-boss.tech"
                        - "https://cdnjs.cloudflare.com/"
                -   name: "object-src"
                    value:
                        - "'none'"
                -   name: "frame-ancestors"
                    value:
                        - "'self'"
    -
        scope:
            path:	""
            type:	"posts"
        values:
            layout:	"post"
            content-security-policy:
                -   name: "script-src"
                    value:
                        - "'self'"
                        - "https://exe-boss.tech"
                        - "https://unpkg.com"
                        - "https://cdnjs.cloudflare.com"
                -   name: "style-src"
                    value:
                        - "'self'"
                        - "'unsafe-inline'"
                        - "https://exe-boss.tech"
                        - "https://cdnjs.cloudflare.com"
                -   name: "object-src"
                    value:
                        - "'none'"
                -   name: "frame-ancestors"
                    value:
                        - "'self'"

# WHO IN THE F# (the programming language) DOESN’T SUPPORT TABS IN 2018? '	' <- tab
# P.S.: F# (the programming language) also doesn’t support tabs, and that’s terrible
